CREATE OR ALTER PROCEDURE sp_update_users_by_id
(
	@USER_ID INT,
	@USER_NAME VARCHAR(150),
	@USER_PASSWORD VARCHAR(150),
	@USER_EMAIL VARCHAR(150),
	@USER_REGISTER_DATE DATETIME,
	@USER_IS_ACTIVE BIT
)
AS BEGIN
BEGIN TRY

	DECLARE @prev_xstate int = XACT_STATE()
	
	IF @prev_xstate = -1 
		ROLLBACK TRANSACTION
	ELSE IF @prev_xstate = 0
		BEGIN TRANSACTION
	ELSE 
		SAVE TRANSACTION sp_update_user

	UPDATE Users 
	SET 
		USER_NAME = @USER_NAME, 
		USER_PASSWORD = USER_PASSWORD, 
		USER_EMAIL = @USER_EMAIL,
		USER_REGISTER_DATE = @USER_REGISTER_DATE,
		USER_IS_ACTIVE = @USER_IS_ACTIVE
	WHERE
	USER_ID = @USER_ID

	DECLARE @curr_xstate int = XACT_STATE()
	
	IF @curr_xstate = 1
		COMMIT TRANSACTION
	
END TRY
BEGIN CATCH
	
	EXEC dbo.sp_insert_error_log

	IF @curr_xstate = -1 
		ROLLBACK TRANSACTION
	ELSE IF @curr_xstate = 1 AND @prev_xstate = 0
		ROLLBACK TRANSACTION
	ELSE IF @curr_xstate = 1 AND @prev_xstate = 1
		ROLLBACK TRANSACTION sp_update_user

END CATCH
END