CREATE TABLE [ErrorLogs] (
  [ERROR_ID] INT IDENTITY(1, 1),
  [USER_NAME] VARCHAR(100),
  [ERROR_NUMBER] INT,
  [ERROR_STATE] INT,
  [ERROR_SEVERITY] INT,
  [ERROR_LINE] INT,
  [ERROR_PROCEDURE] VARCHAR(MAX),
  [ERROR_MESSAGE] VARCHAR(MAX),
  [ERROR_DATETIME] DATETIME
)

GO