CREATE TABLE [Passwords] (
  [PASSWORD_ID] INT IDENTITY(1, 1),
  [USER_ID] INT NOT NULL,
  [PASSWORD_TYPE_ID] INT NOT NULL,
  [PASSWORD_CREATE_DATE] DATETIME NOT NULL,
  [PASSWORD_EXPIRY_DATE] DATETIME NOT NULL
)

GO

ALTER TABLE [passwords] ADD PRIMARY KEY(PASSWORD_ID)

GO

ALTER TABLE [passwords] ADD FOREIGN KEY ([PASSWORD_TYPE_ID]) REFERENCES [PassworTypes] ([PASSWORD_TYPE_ID])

GO

ALTER TABLE [passwords] ADD FOREIGN KEY ([USER_ID]) REFERENCES [Users] ([USER_ID])

GO